[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
image = {version = "0.25.5", features = ["avif-native"]}
gainforge = {path = "../"}
jpeg-decoder = {path = "./jpeg-decoder"}
turbojpeg = "1.2.2"
num-traits = "0.2.19"